
---
name: RUN

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start-sunshine:
    name: start sunshine
    runs-on: windows-latest
    steps:
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: cmake gcc-g++ wget unzip
    - name: run
      run: |
          wget https://github.com/wtfloltk/Sunshine/actions/runs/7953319279/artifacts/1255174012
          unzip sunshine-windows.zip
          unzip sunshine-windows-portable.zip
          cd Sunshine
          .\sunshine.exe
